baseURL = "/"
languageCode = "en-us"
title = "Influencer identity"
theme = "identity"

disableKinds = [
	"page", 
	"section", 
	"taxonomy", 
	"taxonomyTerm", 
	"RSS", 
	"sitemap", 
	"robotsTXT", 
]

[params]
  favicon_ico = "icons/favicon.ico"
  favicon_ico_sizes = "16x16 32x32"
  appleicon = "apple.png"

  [[params.social]]
    title = "Instagram"
    icon = "fa-instagram"
    link = "https://www.instagram.com/youridentity.io/"
    target = "_blank"

  [params.footer]
    copyright = "youridentity.io"

  [[params.credits]]
    title = "youridentity.io"
    text = "Design by"
    link = "https://your-identity.netlify.app"