backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/imgages
public_folder: /imgages
collections:
  - name: 'Landing Page'
    label: 'Blog'
    folder: 'content/'
    create: true
    slug: '_index.md'
    editor:
      preview: false
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Job Title', name: 'position', widget: 'string' }
      - { label: 'Location', name: 'livesIn', widget: 'string' }
      - { label: 'Avatar', name: 'avatar', widget: 'image' }