backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/images
public_folder: /images
collections:
  - name: 'index'
    label: 'Landing Page'
    folder: 'content/'
    create: false
    slug: '_index.md'
    editor:
      preview: false
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Job Title', name: 'position', widget: 'string' }
      - { label: 'Location', name: 'livesIn', widget: 'string' }
      - { label: 'Avatar', name: 'avatar', widget: 'image' }
      - { label: 'Headlines', name: 'scope', widget: 'list', field: {name: 'hedaline', label: 'Headline', widget: 'markdown'}}
      - { label: 'Biography', name: 'biography', widget: 'markdown' }